export const global_types = {
  SET_ACTIVE_ALGORITHM: "SET_ACTIVE_ALGORITHM",
  SET_ACTIVE_MAZE: "SET_ACTIVE_MAZE",
  START_ALGORITHM_ANIMATION: "START_ALGORITHM_ANIMATION",
  END_ALGORITHM_ANIMATION: "END_ALGORITHM_ANIMATION",
  END_MAZE_ANIMATION: "END_MAZE_ANIMATION",
  RESTART_GRID: "RESTART_GRID",
};
