export const global_types = {
  SELECT_PATHFINDING_ALGORITHM: "SELECT_PATHFINDING_ALGORITHM",
  SELECT_MAZE_ALGORITHM: "SELECT_MAZE_ALGORITHM",
  SELECTED_PATHFINDING_ALGORITHM_ACTIVE:
    "SELECTED_PATHFINDING_ALGORITHM_ACTIVE",
  SELECTED_MAZE_ALGORITHM_ACTIVE: "SELECTED_MAZE_ALGORITHM_ACTIVE",
  SELECTED_PATHFINDING_ALGORITHM_ON_GRID:
    "SELECTED_PATHFINDING_ALGORITHM_ON_GRID",
  SELECTED_MAZE_ALGORITHM_ON_GRID: "SELECTED_MAZE_ALGORITHM_ON_GRID",
  OBSTACLES_ON_GRID: "OBSTACLES_ON_GRID",
  NO_POSSIBLE_PATH_MESSAGE: "NO_POSSIBLE_PATH_MESSAGE",
  NO_POSSIBLE_PATH: "NO_POSSIBLE_PATH",
  RESTART_GRID_ACTIVE: "RESTART_GRID_ACTIVE",
};
